[package]
name = "trex-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
futures.workspace = true
object_store = { workspace = true, features = ["aws", "fs"] }
redis = { workspace = true, features = ["tokio-comp", "connection-manager"] }
sqlx = { workspace = true, features = ["runtime-tokio", "tls-rustls-aws-lc-rs", "postgres", "migrate", "macros"] }
uuid.workspace = true

[dev-dependencies]
dotenvy.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
